inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'Dangerfile'
    - 'Dangerfile.spec'
  NewCops: enable

Rails:
  Exclude:
    - 'app/models/master/**/*'

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - 'spec/requests/**/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/AnyInstance:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style:
  Exclude:
    - 'db/schema.rb'
